// LUZ DEVORA ORTIZ SALAZAR
// ING. ANIMACION DIGITAL
// ID:599045
Algoritmo CON02
	Definir N1, N2, N3 Como Real
	Escribir 'INTRODUSCA UN NUMERO '
	Leer N1
	Escribir 'INTRODUSCA OTRO NUMERO'
	Leer N2
	Escribir 'INRODUSCA OTRO NUMERO'
	Leer N3
	Si N1<N2 Y N2<N3 Entonces
		Escribir 'LOS NUMERO SE HAN INTRODUCIDO EN ORDEN ACENDENTE '
	SiNo
		Escribir 'LOS NUMERO NO HAN SIDO INTRODUCIDOS DE MANERA ACENDENTE'
	FinSi
FinAlgoritmo
