//ORTIZ SALAZAR LUZ DEVORA 
//ING ANIMACION 
//599045
Algoritmo P1A13_17
	Definir MET, MIN, SEG,VM Como Real;
	MIN<-1
	SEG<-1
	Mientras MIN <>0 Y SEG <>0
		
	
	Escribir "PORFAVOR DIGITE LOS MINUTOS ";
	LEER MIN;
	eSCRIBIR "PRFAVOR DIGITE LOS SEGUNDOS ";
	Leer SEG;
	SI MET<>0 Y SEG<> 0 ENTONCES
	
	MET<- 1500;
	VM<- MET/((MIN*60)+SEG);
	
	ESCRIBIR "LA VELOCIDAD DEL COOREDOR ES: ", VM,"M/S"
	FIN SI
FinMientras

FinAlgoritmo
